### PR TITLE
Allow symfony6

### PR DESCRIPTION
**Pull request by 77web**
We want to update our project using this bundle to Symfony6.
So please allow Symfony6 🤗

### CODE REVIEW

**Comment by 77web** [comment]
in lowest deps CI, Symfony3.4 KernelTestCase does not comply phpunit signature 🤔

**Comment by 77web** [comment]
@ttskch Please review :pray:

**Comment by ttskch** [comment]
@77web
Thanks a lot!

I found that [symfony/framework-bundle 4.2.3- are not compatible with phpunit8](https://github.com/symfony/framework-bundle/commit/2b7214fb50dab839f960c8093754061d82b759a2).

And in the first place, unfortunately, this library cannot be tested with Symfony 5.0- and Symfony 5.1+ at the same time because of [a BC Breaking in Symfony 5.1+](https://github.com/ttskch/TtskchPaginatorBundle/blob/fcf54b611a5fcaf78798ee60b5bbb6325a4a1a85/tests/TestKernel.php#L31-L35).

So could you please do following?

* don't remove `symfony/framework-bundle` from `require-dev`
* modify `require-dev > symfony/framework-bundle` from `^5.2` to `^5.1|^6.0`

> I don't know why I specified not `^5.1` but `^5.2` originally😅

Thanks.

**Comment by siketyan** [comment]
Suggestion:
```php
if (\Symfony\Component\HttpKernel\Kernel::VERSION_ID >= 50100) {
    protected function configureContainer(ContainerConfigurator $c)
    {
        $c->import(__DIR__.'/Resources/config/test.yaml');
    }
) else {
    protected function configureContainer(ContainerBuilder $c, LoaderInterface $loader)
    {
        // I do not care this works
        $loader->load(__DIR__.'/Resources/config/test.yaml');
    }
}
```

**Comment by ttskch** [comment]
@siketyan OMG. I'm trying that after this. Thanks!

**Comment by ttskch** [comment]
@77web Thanks!

**Pull request merged**
